# Generated by Django 3.2.2 on 2021-05-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='orgImgLink',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='orgLink',
            field=models.TextField(default=''),
        ),
    ]
