# Generated by Django 3.2.2 on 2021-05-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20210511_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='orgImgLink',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='orgLink',
            field=models.TextField(blank=True, default=''),
        ),
    ]
